package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TbaMemberinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.username
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.id
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.pwd
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.email
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.lname
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private String lname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.balance
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.status
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.regdate
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private Date regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.activedate
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private Date activedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tba_memberinfo.remark
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tba_memberinfo
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.username
     *
     * @return the value of tba_memberinfo.username
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.username
     *
     * @param username the value for tba_memberinfo.username
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.id
     *
     * @return the value of tba_memberinfo.id
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.id
     *
     * @param id the value for tba_memberinfo.id
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.pwd
     *
     * @return the value of tba_memberinfo.pwd
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.pwd
     *
     * @param pwd the value for tba_memberinfo.pwd
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.email
     *
     * @return the value of tba_memberinfo.email
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.email
     *
     * @param email the value for tba_memberinfo.email
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.lname
     *
     * @return the value of tba_memberinfo.lname
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.lname
     *
     * @param lname the value for tba_memberinfo.lname
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.balance
     *
     * @return the value of tba_memberinfo.balance
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.balance
     *
     * @param balance the value for tba_memberinfo.balance
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.status
     *
     * @return the value of tba_memberinfo.status
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.status
     *
     * @param status the value for tba_memberinfo.status
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.regdate
     *
     * @return the value of tba_memberinfo.regdate
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.regdate
     *
     * @param regdate the value for tba_memberinfo.regdate
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.activedate
     *
     * @return the value of tba_memberinfo.activedate
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public Date getActivedate() {
        return activedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.activedate
     *
     * @param activedate the value for tba_memberinfo.activedate
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setActivedate(Date activedate) {
        this.activedate = activedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tba_memberinfo.remark
     *
     * @return the value of tba_memberinfo.remark
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tba_memberinfo.remark
     *
     * @param remark the value for tba_memberinfo.remark
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tba_memberinfo
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbaMemberinfo other = (TbaMemberinfo) that;
        return (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPwd() == null ? other.getPwd() == null : this.getPwd().equals(other.getPwd()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getLname() == null ? other.getLname() == null : this.getLname().equals(other.getLname()))
            && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRegdate() == null ? other.getRegdate() == null : this.getRegdate().equals(other.getRegdate()))
            && (this.getActivedate() == null ? other.getActivedate() == null : this.getActivedate().equals(other.getActivedate()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tba_memberinfo
     *
     * @mbggenerated Mon Dec 29 20:01:04 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPwd() == null) ? 0 : getPwd().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getLname() == null) ? 0 : getLname().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRegdate() == null) ? 0 : getRegdate().hashCode());
        result = prime * result + ((getActivedate() == null) ? 0 : getActivedate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}